package main

import (
	T "html/template"
	"os"
)

const (
	template = `
<html>
<head>
	<link href="http://fonts.googleapis.com/css?family={{.FontName}}" rel="stylesheet" type="text/css">
</head>
<body>
	{{.Script}}
	{{.Safe}}
</body>
</html>
`
)

func main() {
	context := struct {
		FontName string
		Script   string
		Safe     T.HTML
	}{
		"Pathway Gothic One",
		"<script>alert('i haz ur cookies');</script>",
		T.HTML("<script>console.log('generated by application')</script>"),
	}

	t := T.Must(T.New("thestdlib").Parse(template))
	t.Execute(os.Stdout, context)
}
